### PR TITLE
chore: unit tests / added workers queuing

### PR DESCRIPTION
**Pull request by jdutchak**
**Description**

This PR fixes # adding unit tests and workers queue

**Notes for Reviewers**
In workers.go in the SendWork workflow

I have added a Response Collector that will continue collecting responses until all responses have been exhausted or 60 seconds has commenced. On every response each will be added to the workers response queue. When all responses are collected they are then sent to the workerDoneCh to be packaged as a new block on the chain. The chain is updated and the latest version of the chain persisted on IPFS. 

The blocks can be explored by calling the validator node endpoint -> /api/v1/blocks
A single hash can be explored by calling the validators node endpoint -> /api/v1/blocks/:hash

From here we can work out handling errors from services scraped like 429, or authentication errors as needed. 

The final response should be the expected clean output ie twitter profile, twitter followers, a websites data, discord etc...

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by jdutchak** [comment]
dev-env

**Review by 5u6r054 — APPROVED** [review]

**Comment by teslashibe** [comment]
@jdutchak how will this work with forward thinking of selecting a sub-set of workers to do the work rather than getting a response from **_all_** workers. Does this allow for scaling into sharded pools of workers so not all workers get hit by all request every time? 

Secondly what does a solution look like with this to address the local worker erroring out and stopping the work continuing to the network which @restevens402 has been working on?

**Comment by teslashibe** [comment]
Also @jdutchak what ticket does this relate to on the board? I don't see a ticket for this?

**Comment by teslashibe** [comment]
https://www.loom.com/share/1c0074d94bbf450683fa2ca1860affcc

**Comment by jdutchak** [comment]
`how will this work with forward thinking of selecting a sub-set of workers to do the work rather than getting a response from all workers. Does this allow for scaling into sharded pools of workers so not all workers get hit by all request every time?`

- This commit was a P0 fix to stabilize - the above can now be planned in a spike from a proper functioning flow. This has been tested on a dev environment, a local net environment, on test with the assistance of JDurkin and Giovanni.

`Secondly what does a solution look like with this to address the local worker erroring out and stopping the work continuing to the network which @restevens402 has been working on here https://github.com/masa-finance/masa-oracle/tree/fix/68?`

- This commit solves this - fix/68 is not required
- In summary. This commit solves the proper aggregation of work responses in order to handle errors, timeouts, 429s, invalid logins. I have tested with an (ON) having bad (TW) creds and 1 (ON) having none and 1 (BNVS) with creds and results were no issues and no errors in the final response. 

`what ticket does this relate to on the board? I don't see a ticket for this so assume this has not been groomed?`

- I lost track where this "issue" was listed but it was inside some spike or request Ettore might know. My goal was to  focus on getting this resolved as a P0 priority to unblock everyone and the user base which IMO was the most important way to proceed. Now we can take a moment and feel comfortable in moving forward with formal planning and added feature set around this feature and next steps. 

The time, thought, and complexity made this a fun and challenging task!

Note: it is important to push this version to the users on the test env asap as previous code could still self report improper node data that could very well lead to what appears as bugs. I feel fairly confident this all works as expected and if all peers have the correct config settings (envs) and updated code we will be stable and can move forward.

**Comment by teslashibe** [comment]
Thanks @jdutchak appreciate the thorough response. 

Based on this comment we should make sure we increment version in some way to completely wipe nodeData and all chain state. cc @5u6r054 

@mudler I will add this to our release checklist as a step for this next release.

`Note: it is important to push this version to the users on the test env asap as previous code could still self report improper node data that could very well lead to what appears as bugs. I feel fairly confident this all works as expected and if all peers have the correct config settings (envs) and updated code we will be stable and can move forward.`

**Comment by mudler** [comment]
> @mudler I will add this to our release checklist as a step for this next release.
> 
> `Note: it is important to push this version to the users on the test env asap as previous code could still self report improper node data that could very well lead to what appears as bugs. I feel fairly confident this all works as expected and if all peers have the correct config settings (envs) and updated code we will be stable and can move forward.`

I think we have it already, it's https://github.com/masa-finance/roadmap/issues/67, isn't it?

**Comment by jdutchak** [comment]
> Thanks @jdutchak appreciate the thorough response. @restevens402 and I were still seeing errors with `accumutedUptime` being overstated. I am assuming here that this is a separate matter to the fixes contained in here? Am I thinking of this correctly.
> 
> Based on this comment we should make sure we increment version in some way to completely wipe nodeData and all chain state so we have a clean slate for testing as @jdutchak states - cc @5u6r054
> 
> @mudler I will add this to our release checklist as a step for this next release.
> 
> `Note: it is important to push this version to the users on the test env asap as previous code could still self report improper node data that could very well lead to what appears as bugs. I feel fairly confident this all works as expected and if all peers have the correct config settings (envs) and updated code we will be stable and can move forward.`

Since nodes self report their uptime, it is most likely that this is from nodes running with code before the fix: way to verify this is if the uptime for nodes with updated fixes for this issue are correct and some others are not. I do not think this is still an issue but not 100% sure.

**Review by theMultitude — APPROVED** [review]
Hopefully gets us up and running!

**Pull request merged**
