### PR TITLE
Finalizing

### PR DESCRIPTION
**Pull request by jdutchak**
WIP

- Actor Workflows ✓ 
- Rewards ( will move this to its own Issue and PR )
- LLMs  -- endpoint: https://llm-dev.masa.finance/api/chat ✓ 
- Protobuffers ✓ 
- Scrapers 
  - Twitter ✓ 
  - Web ✓ 
  
- Consensus ( will move this to its own Issue and PR )
  - node must be staked  ✓ 
  - un-staked / staked participate and infer the quality of their requests
  - node uptime ie epoch/period
  - staked / un-staked
  - how much staked
  - participation rate
  - let staked nodes rate each other
  - let un-staked nodes rate each other
  - totalBytes scraped
 
* Flags added ✓ 
  * --twitterScraper
  * --webScraper

### CODE REVIEW

**Comment by jdutchak** [comment]
added completed worker topic with persisting data on dht - needs validation once deployed to dev and test 
also, we want to make clean and clear out existing CACHE resolver on writer nodes with a bugfix in this commit.

**Review by restevens402 — APPROVED** [review]
Great work. No issues.

**Review by 5u6r054 — APPROVED** [review]
Exciting!

**Comment by 5u6r054** [comment]
Probably the simplest way to do this is to cycle those machines and have them come up fresh

**Comment by 5u6r054** [comment]
Right now they're just automatically doing the regular deploy restart

**Pull request merged**
