### PR TITLE
wip claude event tracking

### PR DESCRIPTION
**Pull request by jdutchak**
- finished discovery refactor with network failure backoff and retry methodology
- completed alpha of masa oracle cli - make build will create a separate masa-oracle-cli binary in the bin folder
- to run against a masa oracle node running v alpha-0.0.10
- to run locally see .env.example for all variables needed

NOTE - we tend to get this error during testing -- so if you receive an error "failed to fetch tweets" its actually this 

"Login failed" error="login failed: response status 429 Too Many Requests: {\"code\":88,\"message\":\"Rate limit exceeded.\"}"

### CODE REVIEW

**Comment by jdutchak** [comment]
Updated oracle client interface - WIP

Screenshot 2024-03-25 at 12 08 57 PM

**Comment by jdutchak** [comment]
This is ready to merge to dev with client ui alpha 1 and network backoff discover rework to recover from network fail and recovery.

**Comment by jdutchak** [comment]
logging of network fail and recovery on local test net 

Screenshot 2024-03-26 at 4 42 22 PM

**Review by restevens402 — APPROVED** [review]
All good. Much improved without all the staking checks and improved discovery & DHT.

**Pull request merged**
