### PR TITLE
Client UI v0.0.2-alpha

### PR DESCRIPTION
**Pull request by jdutchak**
Working on formal client UI

### CODE REVIEW

**Comment by jdutchak** [comment]
formal UI rework - WIP

ui

**Comment by jdutchak** [comment]
Concurrent Actor Framework ref: https://en.wikipedia.org/wiki/Actor_model

actormodel

**Comment by teslashibe** [comment]
@restevens402 are you good to review?

**Review by restevens402 — APPROVED** [review]
This looks great. I'm super excited about where this is going

**Pull request merged**
